[project]
name = "nlptask"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "google-generativeai>=0.8.5",
    "nltk>=3.9.1",
    "requests>=2.32.3",
]
